<?php

namespace OC\PlatformBundle\Repository;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{

    public  function  getAdverts($page, $nbPerPage){

        $query = $this->createQueryBuilder('a')
            //Jointure avec image
            ->leftJoin('a.image', 'i')
            ->addSelect('i')
            //Jointure avec categories
            ->leftJoin('a.categories', 'c')
            ->addSelect('c')
            ->orderBy('a.date', 'DESC')
            ->getQuery()
        ;

        $query
            ->setFirstResult(($page-1)*$nbPerPage)
            ->setMaxResults($nbPerPage)
        ;
        return new Paginator($query, true);

    }
    public function getAdvertWithCategories(array $categoryNames){

        $qb = $this
            ->createQueryBuilder('a')
            ->join('a.categories', 'c')
            ->addSelect('c')
        ;

        $qb->where($qb->expr()->in('c.name', $categoryNames));


        return $qb->getQuery()->getResult();

    }
    
}
